#
# Example GitHub Actions config for UW-IT AXD2 app testing and publishing to PyPi
#
# Preconditions:
#
#  1) Application test suite is kicked off by DIR_NAME/test.py
#
#  2) Application contains a setup.py file
#
#  3) Application repo has access to the required secret
#     at https://github.com/organizations/uw-it-aca/settings/secrets:
#
#     PYPI_API_TOKEN
#
# To adapt this config to a specific Python app:
#
#  1) Set DIR_NAME to the name of the package name/directory.
#
#  2) Verify that the lists of branches for push/pull_request is appropriate,
#     and add other branch names if needed.
#
---
name: 'Lint and Test'

env:
  DIR_NAME: uw_spotseeker

on:
  push:
    branches: [main, qa, develop, django-upgrade]
  pull_request:
    branches: [main, qa, develop, django-upgrade]
    types: [opened, reopened, synchronize]
  release:
    branches: [main]
    types: [published]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install commonconf nose2 coverage coveralls==3.3.1

      - name: Run Python Linters
        uses: uw-it-aca/actions/python-linters@main
        with:
          app_name: ${DIR_NAME}

      - name: Run Tests
        run: |
          python -m compileall ${DIR_NAME}/
          coverage run ${DIR_NAME}/test.py -v

      - name: Report Test Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: coveralls
